name: hello3b
on:
  workflow_call:
jobs:
  h:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - run: echo hello3b-perms-only
